# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: SysAdminDoc.AstraDownloader
PackageVersion: 2.12.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: portable
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/SysAdminDoc/AstraDownloader/releases/download/v2.12.0/AstraDownloader.exe
  InstallerSha256: dc48b84e1f29d545689b864d801e04df795263d7aa32e046a71eeb60f08e4b65
ManifestType: installer
ManifestVersion: 1.12.0
