#!/usr/bin/env python3
"""Fail when a user-facing string is added without reaching the catalogues.

The catalogue source list was hand-written, so it drifted to 21 entries
against a window showing 138 and nothing noticed: the generator writes a
missing entry out as its own English source, which Qt needs for a clean
fallback but which also makes an empty catalogue byte-identical in shape to a
finished one.

This gate closes that loop. It re-extracts the strings from the GUI and
checks that:

  * every extracted string has a <message> in every shipped .ts catalogue;
  * no catalogue carries a key the GUI no longer has (a stale key is a
    translation nobody will ever see, and it hides real coverage);
  * the reference locale is complete, so at least one locale proves the
    pipeline end to end;
  * every locale exposed by the picker clears the non-English translation
    floor; partial catalogues may remain for legacy configurations.

It deliberately does NOT require every locale to be complete. Translating
into a language you do not read is how a UI ends up confidently wrong, and
the incomplete locales are tracked as work needing native review.
"""

import sys
# Stdlib ElementTree, as in build-companion-translations.py which writes
# these same files. The only inputs are the .ts catalogues committed to this
# repository and regenerated by that script, and this gate runs at
# development time and ships in no artifact — there is no untrusted document
# on this path. Reading a .ts from anywhere else would need defusedxml.
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TRANSLATIONS_DIR = ROOT / "astra_downloader" / "translations"
sys.path.insert(0, str(Path(__file__).resolve().parent))

from extract_companion_strings import extract_all  # noqa: E402

# The locale that must be complete. German is the one the GUI render
# scenarios drive, so it is the locale a regression would actually surface.
REFERENCE_LOCALE = "de"
# Keep this policy in sync with i18n.py. Partial catalogues remain shipped for
# old configurations, but only these locales are presented to new users.
ADVERTISED_LOCALES = ("de", "en")
COMPANION_LOCALE_MIN_COVERAGE = 0.80


def catalogue_sources(path):
    """The <source> strings declared in one .ts file."""
    root = ET.parse(path).getroot()
    return [
        element.text or ""
        for element in root.iter("source")
    ]


def translated_coverage(path, expected):
    """Count non-English translations, excluding generated fallback entries."""
    expected = set(expected)
    translated = 0
    for message in ET.parse(path).getroot().iter("message"):
        source = message.findtext("source") or ""
        translation = message.findtext("translation") or ""
        if source in expected and translation.strip() and translation != source:
            translated += 1
    return translated, len(expected)


def main():
    expected = extract_all()
    if not expected:
        print("[check-companion-translations] FAIL — extracted no strings at "
              "all; the extractor is broken, not the catalogues")
        return 1
    expected_set = set(expected)
    problems = []
    catalogues = sorted(TRANSLATIONS_DIR.glob("astra_downloader_*.ts"))
    if not catalogues:
        print("[check-companion-translations] FAIL — no .ts catalogues found")
        return 1
    for path in catalogues:
        locale = path.stem.replace("astra_downloader_", "")
        declared = set(catalogue_sources(path))
        missing = expected_set - declared
        stale = declared - expected_set
        if missing:
            problems.append(
                f"{locale}: {len(missing)} string(s) reach the UI but are not "
                f"in the catalogue, first: {sorted(missing)[0]!r}"
            )
        if stale:
            problems.append(
                f"{locale}: {len(stale)} catalogue key(s) no longer exist in "
                f"the UI, first: {sorted(stale)[0]!r}"
            )
    for locale in ADVERTISED_LOCALES:
        path = TRANSLATIONS_DIR / f"astra_downloader_{locale}.ts"
        if not path.exists():
            problems.append(f"{locale}: advertised locale has no catalogue")
            continue
        if locale == "en":
            # English is the source language, so its generated fallback
            # catalogue is complete by definition rather than by translation.
            continue
        translated, total = translated_coverage(path, expected_set)
        ratio = translated / total if total else 0.0
        if ratio < COMPANION_LOCALE_MIN_COVERAGE:
            problems.append(
                f"{locale}: advertised coverage {translated}/{total} "
                f"({ratio:.1%}) is below the "
                f"{COMPANION_LOCALE_MIN_COVERAGE:.0%} floor"
            )
    if problems:
        print("[check-companion-translations] FAIL")
        for problem in problems:
            print(f"  {problem}")
        print("  Run: py -3.13 scripts/build-companion-translations.py")
        return 1
    print(
        f"[check-companion-translations] OK — {len(expected)} UI strings are "
        f"declared in all {len(catalogues)} catalogues"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
